let roundWin = new Audio('audio/roundWin.mp3');
let roundLose = new Audio('audio/roundLose.mp3');
let matchWin = new Audio('audio/matchWin.mp3');
let matchLose = new Audio('audio/matchLose.mp3');
let draw = new Audio('audio/draw.mp3')
let newRound = new Audio('audio/newRound.mp3');
let endRound = new Audio('audio/endRound.mp3');
let restartRound = new Audio('audio/restartRound.mp3')
let bgm = document.getElementById("bgm");